[custom.all.refined]
type = "local"
path = "."
ipkg = "refined.ipkg"

[custom.all.refined-docs]
type = "local"
path = "docs"
ipkg = "docs.ipkg"

[custom.all.elab-util]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "latest:main"
ipkg   = "elab-util.ipkg"
