[custom.all.refined]
type = "local"
path = "."
ipkg = "refined.ipkg"

[custom.all.refined-docs]
type = "local"
path = "docs"
ipkg = "docs.ipkg"

[custom.all.refined-json]
type = "local"
path = "json"
ipkg = "refined-json.ipkg"
test = "test/test.ipkg"

[custom.all.refined-json-test]
type = "local"
path = "json/test"
ipkg = "test.ipkg"

[custom.all.elab-util]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "latest:main"
ipkg   = "elab-util.ipkg"

[custom.all.algebra]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-algebra"
commit = "latest:main"
ipkg   = "algebra.ipkg"
