[custom.all.refined]
type = "local"
path = "."
ipkg = "refined.ipkg"

[custom.all.refined-docs]
type = "local"
path = "docs"
ipkg = "docs.ipkg"

[custom.all.refined-json]
type = "local"
path = "json"
ipkg = "refined-json.ipkg"
test = "test/test.ipkg"

[custom.all.refined-json-test]
type = "local"
path = "json/test"
ipkg = "test.ipkg"

[custom.all.refined-tsv]
type = "local"
path = "tsv"
ipkg = "refined-tsv.ipkg"
test = "test/test.ipkg"

[custom.all.refined-tsv-test]
type = "local"
path = "tsv/test"
ipkg = "test.ipkg"
